GET http://localhost:4000/admin/users?limit=3&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluLTEiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0Njg2MjcyLCJleHAiOjE3NjcyNzgyNzJ9.aeqwgRGt1p5kPwFxZTwxC8a0DA8-4_8REi2wlq4A0H4
Content-Type: application/json
###
GET http://localhost:4000/users/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluLTEiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0Njg2MjcyLCJleHAiOjE3NjcyNzgyNzJ9.aeqwgRGt1p5kPwFxZTwxC8a0DA8-4_8REi2wlq4A0H4
Content-Type: application/json
###

GET http://localhost:4000/users/deactivated
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE5MTcyNWE5LTM4Y2QtNDkyZi1hMWY1LTMyMzU3ZDEyM2EzMSIsImVtYWlsIjoidHRkYXQyM0BjbGMuZml0dXMuZWR1LnZuIiwiaWF0IjoxNzY3NjE5NzY1LCJleHAiOjE3NzAyMTE3NjV9.nCXbT9tCorKXP0Lr4ThfzKINOYkRGcO74zzDUgtjoRM
###

PATCH http://localhost:4000/users/bidder-2/deactivate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE5MTcyNWE5LTM4Y2QtNDkyZi1hMWY1LTMyMzU3ZDEyM2EzMSIsImVtYWlsIjoidHRkYXQyM0BjbGMuZml0dXMuZWR1LnZuIiwiaWF0IjoxNzY3NjE5NzY1LCJleHAiOjE3NzAyMTE3NjV9.nCXbT9tCorKXP0Lr4ThfzKINOYkRGcO74zzDUgtjoRM
###

PATCH http://localhost:4000/users/bidder-1/activate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE5MTcyNWE5LTM4Y2QtNDkyZi1hMWY1LTMyMzU3ZDEyM2EzMSIsImVtYWlsIjoidHRkYXQyM0BjbGMuZml0dXMuZWR1LnZuIiwiaWF0IjoxNzY3NjE5NzY1LCJleHAiOjE3NzAyMTE3NjV9.nCXbT9tCorKXP0Lr4ThfzKINOYkRGcO74zzDUgtjoRM
###

PATCH http://localhost:4000/users/upgrade/bb43988a-e8e4-4f91-b220-1a06c4c7b165/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluLTEiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0MzE2Nzc4LCJleHAiOjE3NjQzMjAzNzh9.zClPkV-oFf_JMtj-0p0xzxDZPOibNDWZihbis61Z3HE
Content-Type: application/json