GET http://localhost:4000/health
###

POST http://localhost:4000/sign-in
Content-Type: application/json

{
	"email": "truongthanhdat6879@gmail.com",
	"password": "123"
}

###
POST http://localhost:4000/sign-up
Content-Type: application/json

{
	"email": "truongthanhdat6879@gmail.com"
}

###
POST http://localhost:4000/verify-email
Content-Type: application/json

{
	"email": "truongthanhdat6879@gmail.com",
	"fullname": "Truong Thanh Dat",
	"password": "123",
	"code": "QMKGC0"
}

###
POST http://localhost:4000/google/authentication
Content-Type: application/json

{
	"email": "bidder5@example.com",
	"fullname": "Thanh Dat"
}

###
GET http://localhost:4000/auth/google
