### TEST đề bài
### 1
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci0xIiwiZW1haWwiOiJiaWRkZXIxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MDc1LCJleHAiOjE3NjcwODYwNzV9.w2xdhSlTRyLrhfOLnQHnACcs2jm6Ql38kBuicyp_jHg
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 11000000
}


### 2
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci0yIiwiZW1haWwiOiJiaWRkZXIyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTE3LCJleHAiOjE3NjcwODYxMTd9.0z6RPT4rKJl1Il0HR72caQhvmr2SplAdpn7YHwirCLw
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 100000000
}


### 3
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci0zIiwiZW1haWwiOiJiaWRkZXIzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTQ2LCJleHAiOjE3NjcwODYxNDZ9.hyyFKOXGmgGkMw0Cwn3_aAqqkNQSK5S2BORPIUGCX24
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 11500000
}

### 4
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci00IiwiZW1haWwiOiJiaWRkZXI0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTgwLCJleHAiOjE3NjcwODYxODB9.zTd-GJMCMInyvIB5sMFZ7nEP3KXDvnt7xmYMrcWGrTg
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 11500000
}

### 4
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci00IiwiZW1haWwiOiJiaWRkZXI0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTgwLCJleHAiOjE3NjcwODYxODB9.zTd-GJMCMInyvIB5sMFZ7nEP3KXDvnt7xmYMrcWGrTg
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 11700000
}



### Lấy danh sách thông tin lịch sử đấu giá
GET http://localhost:4000/autoBid/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb03/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci00IiwiZW1haWwiOiJiaWRkZXI0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTgwLCJleHAiOjE3NjcwODYxODB9.zTd-GJMCMInyvIB5sMFZ7nEP3KXDvnt7xmYMrcWGrTg
Content-Type: application/json


### Đếm lượt ra giá
GET http://localhost:4000/autoBid/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d03/count
Content-Type: application/json



### Lấy giá cao nhất của 1 bidder trên sản phẩm
GET http://localhost:4000/autoBid/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU1YmM3NzY4LTIxNTctNDhiMi1iM2VhLTAxYzYwYzZlZjAzOCIsImVtYWlsIjoibnRkYW5nMjNAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NDY4NjQ0MSwiZXhwIjoxNzY3Mjc4NDQxfQ.58n_addU49bBqw_4kpelC8TNpuz7CJrGJFxIaWy_Cxw


### Lấy lịch sử đấu giá query params
GET http://localhost:4000/autoBid?userId=c1971d57-98bc-448b-a2d8-b139c1c03ba5&productId=?&limit=1&page=2&sort=price_desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU1YmM3NzY4LTIxNTctNDhiMi1iM2VhLTAxYzYwYzZlZjAzOCIsImVtYWlsIjoibnRkYW5nMjNAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NDY4NjQ0MSwiZXhwIjoxNzY3Mjc4NDQxfQ.58n_addU49bBqw_4kpelC8TNpuz7CJrGJFxIaWy_Cxw
##############################


