### TEST đề bài
### 1
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci0xIiwiZW1haWwiOiJiaWRkZXIxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MDc1LCJleHAiOjE3NjcwODYwNzV9.w2xdhSlTRyLrhfOLnQHnACcs2jm6Ql38kBuicyp_jHg
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 11000000
}


### 2
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci0yIiwiZW1haWwiOiJiaWRkZXIyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTE3LCJleHAiOjE3NjcwODYxMTd9.0z6RPT4rKJl1Il0HR72caQhvmr2SplAdpn7YHwirCLw
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 10800000
}


### 3
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci0zIiwiZW1haWwiOiJiaWRkZXIzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTQ2LCJleHAiOjE3NjcwODYxNDZ9.hyyFKOXGmgGkMw0Cwn3_aAqqkNQSK5S2BORPIUGCX24
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 11500000
}

### 4
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci00IiwiZW1haWwiOiJiaWRkZXI0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTgwLCJleHAiOjE3NjcwODYxODB9.zTd-GJMCMInyvIB5sMFZ7nEP3KXDvnt7xmYMrcWGrTg
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 11500000
}

### 4
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci00IiwiZW1haWwiOiJiaWRkZXI0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTgwLCJleHAiOjE3NjcwODYxODB9.zTd-GJMCMInyvIB5sMFZ7nEP3KXDvnt7xmYMrcWGrTg
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 11700000
}

###
GET http://localhost:4000/autoBid/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci00IiwiZW1haWwiOiJiaWRkZXI0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTgwLCJleHAiOjE3NjcwODYxODB9.zTd-GJMCMInyvIB5sMFZ7nEP3KXDvnt7xmYMrcWGrTg
Content-Type: application/json

##############################


### Bidder A return — 11.4M
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci0xIiwiZW1haWwiOiJiaWRkZXIxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDc0OTk4LCJleHAiOjE3NjQ0Nzg1OTh9.eZyIUEUtVXL3pEXS7Oeflg7mklByW6JADRVrf6CWJpI
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 11400000
}


### Bidder D return — 12M
POST http://localhost:4000/autoBid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci00IiwiZW1haWwiOiJiaWRkZXI0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDc1MDgyLCJleHAiOjE3NjQ0Nzg2ODJ9.vF3F6Ekxp1peLNE3otoinN-hOqsvgltOoQqajcQJtas
Content-Type: application/json

{
    "productId": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb08",
    "maxAutoBidAmount": 12000000
}

