GET http://localhost:4000/chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ODUxNTg2LTJjNDMtNGY1OC04NjhiLTdhNTNmZWM5MzExNiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQ2ODc5QGdtYWlsLmNvbSIsImlhdCI6MTc2NjIzODgzNywiZXhwIjoxNzY4ODMwODM3fQ.7B1gFTLpPd_aCfh20kK6elOGJAUOrOIdQVxlCYwR9O8
Content-Type: application/json

###
GET http://localhost:4000/products/test-chat/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ODUxNTg2LTJjNDMtNGY1OC04NjhiLTdhNTNmZWM5MzExNiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQ2ODc5QGdtYWlsLmNvbSIsImlhdCI6MTc2NjI5NjM0OSwiZXhwIjoxNzY4ODg4MzQ5fQ.Ofq5hkc8ejb1uKdNF_E7ND0zPtQ1xkgPcxQtbQpVupg
Content-Type: application/json

###
POST http://localhost:4000/products/test-chat/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ODUxNTg2LTJjNDMtNGY1OC04NjhiLTdhNTNmZWM5MzExNiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQ2ODc5QGdtYWlsLmNvbSIsImlhdCI6MTc2NjI5NjM0OSwiZXhwIjoxNzY4ODg4MzQ5fQ.Ofq5hkc8ejb1uKdNF_E7ND0zPtQ1xkgPcxQtbQpVupg
Content-Type: application/json

{
	"content": "Bạn còn cần thông tin gì nữa không"
}