### Lấy danh sách đơn hàng theo người dùng có vai trò là SELLER
### ADMIN - lấy tất cả đơn
GET http://localhost:4000/orders?page=1&limit=10&view=ADMIN
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NjIyODg0MywiZXhwIjoxNzY4ODIwODQzfQ.X5nKBibERIkfjUciJpp8DusPUTu7sOedT-Z9mRAx8Bk
Content-Type: application/json

### ADMIN - lấy tất cả đơn (có thể search theo tên sản phẩm)
GET http://localhost:4000/orders?page=1&limit=10&view=ADMIN&q=laptop
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NjIyODg0MywiZXhwIjoxNzY4ODIwODQzfQ.X5nKBibERIkfjUciJpp8DusPUTu7sOedT-Z9mRAx8Bk
Content-Type: application/json

### Lấy thông tin của đơn hàng thông qua id của sản phẩm
GET http://localhost:4000/orders/products/90e5ddff-0cc7-4677-8692-56c9ae568d29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NjIyODg0MywiZXhwIjoxNzY4ODIwODQzfQ.X5nKBibERIkfjUciJpp8DusPUTu7sOedT-Z9mRAx8Bk
Content-Type: application/json

### SELLER - lấy đơn theo sản phẩm mình bán (search theo tên sản phẩm)
GET http://localhost:4000/orders?page=1&limit=10&view=SELLER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NjIyODg0MywiZXhwIjoxNzY4ODIwODQzfQ.X5nKBibERIkfjUciJpp8DusPUTu7sOedT-Z9mRAx8Bk
Content-Type: application/json

### BIDDER - lấy đơn mình mua (search theo tên sản phẩm)
GET http://localhost:4000/orders?page=1&limit=10&view=BIDDER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU1YmM3NzY4LTIxNTctNDhiMi1iM2VhLTAxYzYwYzZlZjAzOCIsImVtYWlsIjoibnRkYW5nMjNAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NjQxMTA5MiwiZXhwIjoxNzY5MDAzMDkyfQ.zImIuR_waeQGqZfiJq11ztMl_zozOkYtDMLZq81aTMs
Content-Type: application/json


### Lấy chi tiết đơn hàng theo ID đơn hàng - token của SELLER LND
GET http://localhost:4000/orders/2628edb3-fa92-4822-b54b-ba1903eda38d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NzAyNzk5MCwiZXhwIjoxNzY5NjE5OTkwfQ.csH9ZXmRGDUuVupV9RJvmgw1W_dXJlFnd1i2F2Jndxo
Content-Type: application/json


### Lấy chi tiết đơn hàng theo ID đơn hàng - token của BIDDER LND
GET http://localhost:4000/orders/2628edb3-fa92-4822-b54b-ba1903eda38d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3NTI3MWFlLTIzZmUtNDg2Yy04MDE4LTI5ZTI2NjBjZDY3NyIsImVtYWlsIjoibGVuaHV0ZHV5MTUxMTA1QGdtYWlsLmNvbSIsImlhdCI6MTc2NzAyODA5NSwiZXhwIjoxNzY5NjIwMDk1fQ.42VT-Q74n17s8-kzkmYQ9TLZvZSbOleOdAEJwCR0TbA
Content-Type: application/json


### Cập nhật thông tin ngân hàng (QR)
PATCH http://localhost:4000/orders/2628edb3-fa92-4822-b54b-ba1903eda38d/qr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NzAyNzk5MCwiZXhwIjoxNzY5NjE5OTkwfQ.csH9ZXmRGDUuVupV9RJvmgw1W_dXJlFnd1i2F2Jndxo

{
    "qrInfo": "Ngân hàng Vietcombank - Chủ tài khoản: Lê Nguyễn Đức Huy - Số tài khoản: 123456789",
    "image": "Bỏ file vào đây"
}



### Cập nhật thông tin thanh toán và đĩa chỉ giao hàng
PATCH http://localhost:4000/orders/2628edb3-fa92-4822-b54b-ba1903eda38d/payment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NzAyNzk5MCwiZXhwIjoxNzY5NjE5OTkwfQ.csH9ZXmRGDUuVupV9RJvmgw1W_dXJlFnd1i2F2Jndxo

{
    "buyerAddress": "Xã Thanh Mỹ, Huyện Tháp Mười, Tỉnh Đồng Tháp",
    "buyerPhone": "0914813749",
    "image": "Bỏ file vào đây"
}


### Step = 3 - Cập nhật thông tin vận chuyển
PATCH http://localhost:4000/orders/2628edb3-fa92-4822-b54b-ba1903eda38d/shipping
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NzAyNzk5MCwiZXhwIjoxNzY5NjE5OTkwfQ.csH9ZXmRGDUuVupV9RJvmgw1W_dXJlFnd1i2F2Jndxo

{
    "shippingCode": "123456789",
    "image": "Bỏ file vào đây"
}


### Xác nhận đã nhận hàng (BIDDER)
PATCH http://localhost:4000/orders/2628edb3-fa92-4822-b54b-ba1903eda38d/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3NTI3MWFlLTIzZmUtNDg2Yy04MDE4LTI5ZTI2NjBjZDY3NyIsImVtYWlsIjoibGVuaHV0ZHV5MTUxMTA1QGdtYWlsLmNvbSIsImlhdCI6MTc2NzAyODA5NSwiZXhwIjoxNzY5NjIwMDk1fQ.42VT-Q74n17s8-kzkmYQ9TLZvZSbOleOdAEJwCR0TbA