###
GET http://localhost:4000/product?limti=5&sort=endAt_desc


###
PATCH http://localhost:4000/product/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb05
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci01IiwiZW1haWwiOiJiaWRkZXI1QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0Njg4NzA5LCJleHAiOjE3NjcyODA3MDl9.yCSdwdjZm4Ml6VR0jQUS0pEpvxGpT8kVWzItfxpsMD4
Content-Type: application/json

{

    "description": "Dâng gà vãi đái"
}




### Lấy sản phẩm của seller
GET http://localhost:4000/product?sort=countBids_desc
