###
GET http://localhost:4000/product?limti=5&sort=countBids_desc


###
PATCH http://localhost:4000/product/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb05
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci01IiwiZW1haWwiOiJiaWRkZXI1QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0Njg4NzA5LCJleHAiOjE3NjcyODA3MDl9.yCSdwdjZm4Ml6VR0jQUS0pEpvxGpT8kVWzItfxpsMD4
Content-Type: application/json

{

    "description": "Dâng gà vãi đái"
}




### Lấy sản phẩm của seller
GET http://localhost:4000/product?sellerId=14222c75-169e-4be6-9fc1-fc114507db93

###
GET http://localhost:4000/product?sellerId=14222c75-169e-4be6-9fc1-fc114507db93&limit=5&page=1
### Mua ngay sản phẩm
POST http://localhost:4000/product/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb06/buy-now
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci0yIiwiZW1haWwiOiJiaWRkZXIyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTE3LCJleHAiOjE3NjcwODYxMTd9.0z6RPT4rKJl1Il0HR72caQhvmr2SplAdpn7YHwirCLw
Content-Type: application/json

{
    "phoneNumber": "0987654321",
    "shippingAddress": "123 Đường ABC, Quận 1, TP.HCM"
}



### Mua ngay sản phẩm
POST http://localhost:4000/product/6e7d1a08-8180-432d-af08-77f2def5c309/buy-now
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmNmMxYjFkLWQyNGUtNDdkYS05NGE1LWY5Mjc1OTAwODBmMSIsImVtYWlsIjoidGhhbmh2bmRhbmc0OTA1QGdtYWlsLmNvbSIsImlhdCI6MTc2NzI3ODAxOSwiZXhwIjoxNzY5ODcwMDE5fQ.Jds_WGAKjHdu_ndyG48Ij8MIbRClfLEShdZvEOg5O7M

