###
GET http://localhost:4000/product?limti=5&sort=countBids_desc


###
PATCH http://localhost:4000/product/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb05
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci01IiwiZW1haWwiOiJiaWRkZXI1QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0Njg4NzA5LCJleHAiOjE3NjcyODA3MDl9.yCSdwdjZm4Ml6VR0jQUS0pEpvxGpT8kVWzItfxpsMD4
Content-Type: application/json

{

    "description": "Dâng gà vãi đái"
}




### Lấy sản phẩm của seller
GET http://localhost:4000/product?sellerId=14222c75-169e-4be6-9fc1-fc114507db93

###
GET http://localhost:4000/product?sellerId=14222c75-169e-4be6-9fc1-fc114507db93&limit=5&page=1
### Mua ngay sản phẩm
POST http://localhost:4000/product/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb06/buy-now
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci0yIiwiZW1haWwiOiJiaWRkZXIyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY0NDk0MTE3LCJleHAiOjE3NjcwODYxMTd9.0z6RPT4rKJl1Il0HR72caQhvmr2SplAdpn7YHwirCLw
Content-Type: application/json

{
    "phoneNumber": "0987654321",
    "shippingAddress": "123 Đường ABC, Quận 1, TP.HCM"
}



### Mua ngay sản phẩm
POST http://localhost:4000/product/90e5ddff-0cc7-4677-8692-56c9ae568d29/buy-now
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NTI5Mjc5NCwiZXhwIjoxNzY3ODg0Nzk0fQ.Xz6Z4NIeJlhL_L0Kx3B4S0rVbcLCad4XGm3cPRvhLVI

