GET http://localhost:4000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ODUxNTg2LTJjNDMtNGY1OC04NjhiLTdhNTNmZWM5MzExNiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQ2ODc5QGdtYWlsLmNvbSIsImlhdCI6MTc2MzQ1NTcxNiwiZXhwIjoxNzYzNDU5MzE2fQ.Oq9wFwaYtAPzwRT5lUGH5V-dBTrjQr34KoWQmCExsz8
###

POST http://localhost:4000/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJpZGRlci01IiwiZW1haWwiOiJiaWRkZXI1QGV4YW1wbGUuY29tIiwiaWF0IjoxNzYzNDgxMzg0LCJleHAiOjE3NjM0ODQ5ODR9.xOW9WakSq3hlL3NJO968dF-OfBmaxVKqyEttbOOyvsI
Content-Type: application/json

{
	"fullname": "truong thanh dat"
}