GET http://localhost:4000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc3NzM3MjFlLWU1NjQtNDQ2Ny05MzYyLTAyMWU3OTlhYjI5YiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQwMzA1QGdtYWlsLmNvbSIsImlhdCI6MTc2NTEyMzE4NCwiZXhwIjoxNzY3NzE1MTg0fQ.zNdsFMsC4od5cRcVYE98ndJb-bzfzbcHej_55ybnr80
###
GET http://localhost:4000/users/7773721e-e564-4467-9362-021e799ab29b
Content-Type: application/json
###
GET http://localhost:4000/sellers/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NzI3MDAxNywiZXhwIjoxNzY5ODYyMDE3fQ.iVrfOwLFkDy4InAsUlYNzBcv1agCaAvzogw1tx9IZoE

###
PATCH http://localhost:4000/users/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc3NzM3MjFlLWU1NjQtNDQ2Ny05MzYyLTAyMWU3OTlhYjI5YiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQwMzA1QGdtYWlsLmNvbSIsImlhdCI6MTc2NTEyMzE4NCwiZXhwIjoxNzY3NzE1MTg0fQ.zNdsFMsC4od5cRcVYE98ndJb-bzfzbcHej_55ybnr80
Content-Type: application/json

{ 	
	"dateOfBirth": "2005-05-03"
}
###

POST http://localhost:4000/users/upgrade
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU1YmM3NzY4LTIxNTctNDhiMi1iM2VhLTAxYzYwYzZlZjAzOCIsImVtYWlsIjoibnRkYW5nMjNAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NDcyMjczMywiZXhwIjoxNzY3MzE0NzMzfQ.qPJkGXFvNKxmdri5RTRuJU7zfmHab-hpEIJXTk4V7qo
Content-Type: application/json

{
	"note": "I want to sell an meta quest"
}

###
GET http://localhost:4000/users/blocked/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ODUxNTg2LTJjNDMtNGY1OC04NjhiLTdhNTNmZWM5MzExNiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQ2ODc5QGdtYWlsLmNvbSIsImlhdCI6MTc2NDQyMTkyMywiZXhwIjoxNzY0NDI1NTIzfQ.lTnlJLsdY_-sBCXny9prCCr4ejjv0vXvBXTTZGpwG3o
Content-Type: application/json

###
POST http://localhost:4000/users/bidder-1/blocked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ODUxNTg2LTJjNDMtNGY1OC04NjhiLTdhNTNmZWM5MzExNiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQ2ODc5QGdtYWlsLmNvbSIsImlhdCI6MTc2NDQyMTkyMywiZXhwIjoxNzY0NDI1NTIzfQ.lTnlJLsdY_-sBCXny9prCCr4ejjv0vXvBXTTZGpwG3o
Content-Type: application/json

{
	"productId": "1",
	"reason": "I hate him too"
}

### Comment section
POST http://localhost:4000/products/1/ask
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc3NzM3MjFlLWU1NjQtNDQ2Ny05MzYyLTAyMWU3OTlhYjI5YiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQwMzA1QGdtYWlsLmNvbSIsImlhdCI6MTc2NDY5Njc1MSwiZXhwIjoxNzY3Mjg4NzUxfQ.etBhn1RBEGP45Q6rsEOMJq0kWSjzHnqgtXKjb2zcKRA

{	
	"question": "What is the condition of this product?"
}
###	
POST http://localhost:4000/comments/c0431047-31a3-4479-8bd1-94647d491233/answer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ODUxNTg2LTJjNDMtNGY1OC04NjhiLTdhNTNmZWM5MzExNiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQ2ODc5QGdtYWlsLmNvbSIsImlhdCI6MTc2NTExOTc1MSwiZXhwIjoxNzY3NzExNzUxfQ.BtHa7RbPiOYSqi6FrgjeUKSJUMNBwehGDR2M87moIsA

{
	"productId": "1",
	"answer": "Yes, its brand new."
}
###
GET http://localhost:4000/comments/products/1
Content-Type: application/json
###

DELETE http://localhost:4000/comments/cd7bfbac-9db1-49aa-9d61-0826a02244ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ODUxNTg2LTJjNDMtNGY1OC04NjhiLTdhNTNmZWM5MzExNiIsImVtYWlsIjoidHJ1b25ndGhhbmhkYXQ2ODc5QGdtYWlsLmNvbSIsImlhdCI6MTc2NTEwMDM4NywiZXhwIjoxNzY3NjkyMzg3fQ.juhQXZzKw_KZj9a6JUwM7COE2nQxQSpo2SDWFcsrkBk




### Lấy profile của một user
GET http://localhost:4000/bidder/statistic/c1971d57-98bc-448b-a2d8-b139c1c03ba5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxOTcxZDU3LTk4YmMtNDQ4Yi1hMmQ4LWIxMzljMWMwM2JhNSIsImVtYWlsIjoibG5kdXkyMzJAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc2NzI3MDAxNywiZXhwIjoxNzY5ODYyMDE3fQ.iVrfOwLFkDy4InAsUlYNzBcv1agCaAvzogw1tx9IZoE